### ISSUE TITLE
Code renders like quote-blocks and not code-blocks

### ISSUE THREAD

**Issue by viveknigam3003** [rucio/documentation#11]
## Motivation
The documentation looks good with the Docusaurus theme, but currently the commands or blocks of code are being rendered as 
> Quotes

Instead of 
```
Code
```
While this separated the inline code and the code-blocks from the rest of the text, but using a standard format to display code on Rucio's Documentation would be great for accessibility and aesthetic.

## Modification
To update the Markdown Quote-Blocks used to display code on the website to Code-Blocks for better support and accessibility. 

### Actual Result
http://rucio.cern.ch/documentation/docs/setting-up-rucio-client
![Screenshot (313)](https://user-images.githubusercontent.com/30192068/100618286-a3dd1d00-3341-11eb-9100-7af53600b661.png)

### Expected Result
https://redux.js.org/introduction/getting-started
![Screenshot (312)](https://user-images.githubusercontent.com/30192068/100618022-45b03a00-3341-11eb-8456-664a60d999cd.png)

**Comment by bari12** [comment]
Yes true, feel free to submit a PR for that :-)

**Comment by palakyadav1807** [comment]
I'll work on this.
