### ISSUE TITLE
Upgrading to modern font

### ISSUE THREAD

**Issue by viveknigam3003** [rucio/documentation#12]
## Motivation
Currently the Rucio Documentation website does not explicitly specify any font family, and uses the standard fall-back fonts for displaying the text. This leads to inconsistent look across devices since the website will only use the fall-back fonts for display. While the fall-back fonts should be present in case the primary and the secondary fonts fail to load.

## Modification
Using some modern font pairing will improve the overall theme of the Rucio Documentation. 

* Preferably since the two graphical user interfaces Rucio provides use Inter font family for its typography, the same may be reflected here for consistent theming.
* The [Inter font family](https://fonts.google.com/specimen/Inter) goes well with [Rubik Font](https://fonts.google.com/specimen/Rubik) and they form a pairing. Suggested to use Inter for Headings and Rubik for overline, paragraphs, and body text.

**Comment by bari12** [comment]
Sounds good, I am happy to try that one out.

**Comment by palakyadav1807** [comment]
I'll work on this .
Can you assign this to me?

**Comment by viveknigam3003** [comment]
@palakyadav1807 You can submit a PR according to contribution guidelines. Assignees are managed by @bari12 for this repo 😅

**Comment by palakyadav1807** [comment]
> @palakyadav1807 You can submit a PR according to contribution guidelines. Assignees are managed by @bari12 for this repo 😅

Oh Okay 😕

**Comment by bari12** [comment]
Sure :-) Just submit a PR.
