### ISSUE TITLE
Create a server/daemon installation howto

### ISSUE THREAD

**Issue by bari12** [rucio/documentation#178]
Motivation
----------
We don't really have a good documentation page how to install server & documentation. There are several Google docs roaming around, and some people, such as @cfenell have written a documentation page, but this needs to be properly integrated into the documentation.

Modification
------------

**Comment by cfenell** [comment]
Hi, I tried to add my server setup howto, but I have no write access here.

**Comment by cfenell** [comment]
You can now get it from my fork here: https://github.com/cfenell/rucio-documentation/blob/main/docs/rucio-server-ubuntu.md

**Comment by bari12** [comment]
Hi @cfenell 
Direct writing to the repo is not allowed, but I created a pull request (you can too!) based on your branch for review.
https://github.com/rucio/documentation/pull/181

Thanks a lot!
