### ISSUE TITLE
Missing arrows in request state transition diagram

### ISSUE THREAD

**Issue by airvzxf** [rucio/documentation#188]
# Missing arrows in request state transition diagram

In the web documentation: Home → OperatorTransfers → Transfers Overview, section “[Lifecycle of transfer requests](https://rucio.cern.ch/documentation/transfers-overview)”. Exists a request state transition diagram, in my opinion, it is missing two arrows.

---

The first in the orange state “Failed (F)” which is going to the section “Failed without submission”.

![Missing arrow from failed to failed without submission](https://user-images.githubusercontent.com/831380/225717469-ae58214c-045d-4b7f-8b11-26820992a222.png)

---

The second is a long line from the condition “Less than 3 tiers” when it is “no” to the first condition “use preparer?”.

![Missing arrow from less than 3 tiers, image 1](https://user-images.githubusercontent.com/831380/225718264-ce7409c5-8c0a-4da9-ada5-291ef3949492.png)

![Missing arrow from less than 3 tiers, image 2](https://user-images.githubusercontent.com/831380/225718348-b7a0d7f1-335e-4983-a398-38234c78b859.png)

---

Source code:

- [rucio/documentation: docs/transfers_overview.md](https://github.com/rucio/documentation/blob/main/docs/transfers_overview.md)
- [rucio/documentation: website/static/img/equest_state_transition_chart.svg](https://github.com/rucio/documentation/blob/main/website/static/img/request_state_transition_chart.svg)

**Comment by mlassnig** [comment]
@rcarpa
