### ISSUE TITLE
Search is malfunctioning

### ISSUE THREAD

**Issue by dchristidis** [rucio/documentation#216]
Search results appear, but the URLs are missing one component in the paths. For example, searching for ‘admin’ yields:
https://rucio.cern.ch/documentation/using_the_admin_client/
instead of:
https://rucio.cern.ch/documentation/user/using_the_admin_client/

**Comment by bari12** [comment]
I think this was just a temporary hickup. I changed the pathes recently, but this probably needed to be re-indexed by algolia. Seems to be fine now.
