### ISSUE TITLE
Make visibility of links on pages better

### ISSUE THREAD

**Issue by bziemons** [rucio/documentation#24]
Currently, I do not see a difference in linked text, see

![image](https://user-images.githubusercontent.com/1096713/113857261-9679e880-97a2-11eb-9dfe-f151376e143e.png)

where the last words "Exception definition" are linked to another page.

Modification
----------------

I think it makes sense to modify the existing theme to make links differ from other text.

**Comment by DhruvSondhi** [comment]
@bziemons @bari12 I think so this has been resolved with HTML style hyperlinking :)

**Comment by bziemons** [comment]
@DhruvSondhi thank you! Yes, we already resolved this :)
