### ISSUE TITLE
Ambiguity of "developing" and "developer"

### ISSUE THREAD

**Issue by bziemons** [rucio/documentation#25]
There is a general ambiguity of developing in the documentation as it stands. The distinction between "develop for Rucio" which implies contributing to <https://github.com/rucio/rucio> and "develop with Rucio" which would be using the Rucio clients or the REST API is not clear enough. The latter is actually another form of using Rucio among the existing CLI. There should be a more clear differentiation.

**Comment by esilvaju** [comment]
The suggested solution is:
 
1. Rename the "Developing with Rucio" section to "Rucio client" and keep only content related to Rucio client;
2. Move the part related to the RESTful API to the "REST API Documentation" and append as a section of it;

As can be seen here:[ issue-25](https://github.com/esilvaju/documentation/tree/issue-25)
