### ISSUE TITLE
WebUI: Improve Docs

### ISSUE THREAD

**Issue by ThePhisch** [rucio/documentation#255]
As I am stepping down from being an active developer, I am putting my experience on the WebUI (frontend) into writing for the next person's enjoyment.

**Comment by esilvaju** [comment]
- [ ] Update the README for the new webui containers accordingly to https://github.com/rucio/containers/issues/255#issuecomment-1760448626

**Comment by esilvaju** [comment]
Thanks for you work @ThePhisch ! I can say that I'm enjoying a lot. :)

@bari12 I believe we can close this issue. Feel free to open again if I missed something :)


Regards,

Eraldo
