### ISSUE TITLE
Add Rucio QoS RSE description and instructions

### ISSUE THREAD

**Issue by maatthias** [rucio/documentation#268]
Rucio now supports a quality-of-service (QoS) method for a site to administer at the RSE and therefore storage level a lifetime for its replicas.  A common use case would be to decrease or increase the number of days that replicas sit in a disk buffer in front of tape storage.  This feature allows an operator to set this lifetime on a Rucio RSE.

**Comment by dougbenjamin** [comment]
Will use the S3 documentation page as template for the Rucio QOS documentation - https://github.com/rucio/documentation/blob/main/docs/operator/s3_rse_config.md
