### ISSUE TITLE
Formatting / style guide

### ISSUE THREAD

**Issue by rdimaio** [rucio/documentation#287]
There seems to be a few formatting guidelines in Rucio that are not yet mentioned in the documentation, e.g.:

- The SQLAlchemy query coding style mentioned here: https://github.com/rucio/rucio/pull/6497#discussion_r1494964916
- Sorting imports alphabetically, separating them into sections based on whether they're internal or external dependencies

It would benefit to have a documentation page collecting these guidelines.

**Comment by voetberg** [comment]
Seconding the need for this. I didn't even know there *was* an adopted sql syntax style guide.

**Comment by rdimaio** [comment]
Reopening to address follow-up comments from https://github.com/rucio/documentation/pull/308

**Comment by voetberg** [comment]
@dchristidis 
I would like your opinions in particular on this section - https://github.com/rucio/documentation/blob/main/docs/developer/style_guide.md#sqlalchemy-query-guide 

I tried to keep the queries generic to avoid confusing people with the exact functionality of the queries but this may be a mistake.

**Comment by dchristidis** [comment]
> @dchristidis I would like your opinions in particular on this section - https://github.com/rucio/documentation/blob/main/docs/developer/style_guide.md#sqlalchemy-query-guide

If it is acceptable to you, may I take over and rewrite it?

**Comment by voetberg** [comment]
Please do rewrite! I have no qualms with that.
