### ISSUE TITLE
Make a table for all daemon and its functionality

### ISSUE THREAD

**Issue by panta-123** [rucio/documentation#296]
Idea is to have a single table of all daemon.

Table idea:

```
daemon Name | Daemon Type | Functionality
---------------------------------------------
transmogrifier | Replication | Make replication rule via subcription
repear | Deletion |  Manage file deletion 
```

This will give single view for admin/user/developer .

**Comment by rdimaio** [comment]
Related issue: https://github.com/rucio/documentation/issues/326 - should we close one of the two?

**Comment by panta-123** [comment]
closing this as duplicate.
