### ISSUE TITLE
Certificate of https://rucio.cern.ch/ has expired

### ISSUE THREAD

**Issue by maxnoe** [rucio/documentation#329]
```
❯ curl https://rucio.cern.ch/
curl: (60) SSL certificate problem: certificate has expired
```

![rucio_certificate](https://github.com/rucio/documentation/assets/5488440/89e0b716-f789-4c28-8a9a-a76f1d60760d)

**Comment by mlassnig** [comment]
I have the new certificate, need to deploy.

**Comment by mlassnig** [comment]
Fixed.

**Comment by maxnoe** [comment]
I still get an error

**Comment by rdimaio** [comment]
Works fine for me:

```
❯ curl https://rucio.cern.ch/
<!DOCTYPE HTML>
...
```

![image](https://github.com/rucio/documentation/assets/35903974/59916998-fde7-4a5e-bdba-c0de3f8f9fc7)

@maxnoe do you still get an error?
