### ISSUE TITLE
[Suggestion] Embed gh discussions into the documentation page

### ISSUE THREAD

**Issue by voetberg** [rucio/documentation#351]
Embedding a forum-type discussion directly into the documentation would be a good way to get the community to engage with the gh dicussions (which we haven't had a lot of adoption on) and could be a good resource for people looking for previously asked questions ([similar to how pytorch's discussion boards work](https://discuss.pytorch.org/)]) Existing implementations like [gitcus](https://giscus.app/) could do most of the heavy lifting.

**Comment by bari12** [comment]
This would generate a discussion thread per Doc page?

**Comment by voetberg** [comment]
It could, but we could also have it set up to embed specific discussions (e.g. an FAQ board), or for Feature Request discussion.
