### ISSUE TITLE
Broken link in about section of this repository

### ISSUE THREAD

**Issue by rdimaio** [rucio/documentation#361]
The about section of this repo (https://github.com/rucio/documentation, top right) links to rucio.cern.ch/documentation, which is broken. The correct link is https://rucio.github.io/documentation/

**Comment by voetberg** [comment]
The cern webpage works as well, the github.io is just a mirror

**Comment by rdimaio** [comment]
You're right, not sure why it didn't seem to work before for some reason, but it works for me as well now

**Comment by bari12** [comment]
The main url is rucio.cern.ch/documentation
The github.io one works as well, but we should advertise the cern one.
