### ISSUE TITLE
Inequalities

### ISSUE THREAD

**Issue by ygrange** [rucio/documentation#50]
I'm trying to understand how inequalities work for selection of RSEs. There is something in the docs here:
https://github.com/rucio/documentation/blob/main/docs/rse_expressions.md
However the example does not show how to use the \> or \< operator and I can't really get it to work (but that may be because it seems like the freespace is not exposed in the RSEs we have configured in the ESCAPE data lake). Anyhow I think the example would improve from actually using the operator, but since I don't know the exact details I can't pull-request it.

(also this uses the deprecated expressions flag)

**Comment by bari12** [comment]
An example would really be useful there, I agree.

In rse_expressions you can use comparison operators for any RSE attribute. But if the attribute (e.g `freespace`) is not there, the RSE will just be ignored.
