### ISSUE TITLE
Link to `Replica Management` broken

### ISSUE THREAD

**Issue by dynamic-entropy** [rucio/documentation#70]
`ReplicaManagement.md` does not exist as referenced here (https://github.com/rucio/documentation/blob/240840b1b9f41aad72641b47146560b1a72da38b/docs/Rucio_storage_element.md?plain=1#L36)

Page: https://rucio.cern.ch/documentation/Rucio_storage_element

**Comment by dynamic-entropy** [comment]
I think we meant to use https://github.com/rucio/documentation/blob/main/docs/Replica-management.md instead

**Comment by joeldierkes** [comment]
Resolved by #71
